#
# This profile is for starting the application locally with as few dependencies as possible.
#
server:
  port: 8400 # custom to avoid conflicts with other swiyu components
  shutdown: immediate

jeap:
  security:
    oauth2:
      resourceserver:
        # local mock server
        #authorization-server:
        #  issuer: http://localhost:8480
        #  jwk-set-uri: http://localhost:8480/.well-known/jwks.json

        # dev mock server
        authorization-server:
          issuer: https://swiyu-oauth-mock-server-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch
          jwk-set-uri: https://swiyu-oauth-mock-server-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch/.well-known/jwks.json

        # SWIYU Keycloak Trust Realm (Has to be removed in EID-5658)
        #resource-id: swiyu-trust-management-scs
        #authorization-server:
        #  issuer: https://auth-d.trust-infra.swiyu.admin.ch/realms/bj-swiyu-trust
        #  jwk-set-uri: https://auth-d.trust-infra.swiyu.admin.ch/realms/bj-swiyu-trust/protocol/openid-connect/certs

        # EIAM REF
        #        authorization-server:
        #          issuer: https://identity-eiam-r.eiam.admin.ch/realms/ejpd_bj-swiyu-tms
        #          jwk-set-uri: https://identity-eiam-r.eiam.admin.ch/realms/ejpd_bj-swiyu-tms/protocol/openid-connect/certs

        auth-servers:
          # local mock server
          - issuer: http://localhost:8480
            jwk-set-uri: http://localhost:8480/.well-known/jwks.json
            claim-set-converter-name: null
            authentication-contexts:
              - USER
          # dev mock server
          - issuer: https://swiyu-oauth-mock-server-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch
            jwk-set-uri: https://swiyu-oauth-mock-server-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch/.well-known/jwks.json
            claim-set-converter-name: null
            authentication-contexts:
              - USER
          # EIAM REF
          - issuer: https://identity-eiam-r.eiam.admin.ch/realms/ejpd_bj-swiyu-tms
            jwk-set-uri: https://identity-eiam-r.eiam.admin.ch/realms/ejpd_bj-swiyu-tms/protocol/openid-connect/certs
            claim-set-converter-name: eiamClaimSetConverter
            authentication-contexts:
              - USER
  monitor:
    prometheus:
      user: "prometheus"
      password: "{noop}test"
  messaging:
    kafka:
      bootstrapServers: "http://localhost:9092"
      schemaRegistryUrl: "http://localhost:8081"
      securityProtocol: PLAINTEXT

spring:
  autoconfigure:
    exclude: ch.admin.bit.jeap.monitor.metrics.health.HealthMetricsAutoConfig # since it invokes external health endpoints which are available in local profile
  datasource:
    management-db:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: 'jdbc:postgresql://localhost:5400/trust-management-db'
      username: postgres
      password: secret
    registry-db:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: 'jdbc:postgresql://localhost:5380/trust-registry-db'
      username: postgres
      password: secret
  flyway:
    locations: []  # no afterMigrate script in local dev
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  security:
    oauth2:
      client:
        registration:
          core-business-service-internal:
            provider: mock-oauth-dev
            client-id: swiyu-trust-management-scs-sys
            client-secret: "secret"
            authorization-grant-type: client_credentials
            scope: "openid"
          status-registry-api:
            provider: mock-oauth-dev
            client-id: swiyu-trust-management-scs-b2b-sys
            client-secret: "secret"
            authorization-grant-type: client_credentials
            scope: "openid"
        provider:
          swiyu-keycloak-realm-ecosystem:
            issuer-uri: https://auth-d.trust-infra.swiyu.admin.ch/realms/bj-swiyu-ecosystem
            jwk-set-uri: https://auth-d.trust-infra.swiyu.admin.ch/realms/bj-swiyu-ecosystem/protocol/openid-connect/certs
          mock-oauth-dev:
            issuer-uri: https://swiyu-oauth-mock-server-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch
            jwk-set-uri: https://swiyu-oauth-mock-server-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch/.well-known/jwks.json
          mock-oauth-local:
            issuer-uri: http://localhost:8480
            jwk-set-uri: http://localhost:8480/.well-known/jwks.json
          swiyu-apigw-keycloak:
            authorization-uri: https://keymanager-npr-intra.api.admin.ch/keycloak/realms/APIGW/protocol/openid-connect/auth
            token-uri: https://keymanager-npr-intra.api.admin.ch/keycloak/realms/APIGW/protocol/openid-connect/token
            jwk-set-uri: https://keymanager-npr-intra.api.admin.ch/keycloak/realms/APIGW/protocol/openid-connect/certs


logging:
  level:
    ch.admin: DEBUG
    io.confluent.kafka: ERROR
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
    ch.admin.bit.jeap.messaging.kafka: ERROR
    # for transaction/sql logs see below
    #    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #    org.springframework.transaction: TRACE

management:
  endpoint:
    health:
      show-details: always
      show-components: always

database-migration: # under local development we want to run the migrations on startup
  startup-migrate-mode-enabled: true
  init-container: false

issuer:
  mockClient: true # this will set up the MockIssuerClient instead of the DefaultIssuerClient
  # status-list-uri:
  # - only 1 for now until we have management service with overflow-handling
  # - local setup is not yet implemented, this is just a details url so the app starts
  status-list-uri: "http://localhost:8290/api/v1/statuslist/not-yet-working-status-list.jwt"
  management-api-url: "http://localhost:8080"
  oid4vci-api-url: "http://localhost:8090"
  signing:
    # keys work with the services configured in compose.yml when starting up via local profile
    jwt-signing-key: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIPWav11SgwaMA2ih2JYhKQfTzsBLw8OHWzv22h0sWdJtoAoGCCqGSM49
      AwEHoUQDQgAEDLJwNdAbm2zR32HvLdns8ZKJ4lGNd2K3N+Tv8cn0VZVWKVJRcvcz
      nAWSrvHV+gJZUpl9vhFHsCbLpvOtHfjRkw==
      -----END EC PRIVATE KEY-----
    jwt-signing-key-id: "trust-business-202501201547"

registry:
  trust-registry-data-uri: https://trust-data-service-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch

app:
  frontend:
    environment: local
    auth:
      require-https: false
      use-silent-refresh: false # not supported by the jeap mock service
  functionality:
    automatic-approval-enabled: true
  issuer:
    jwt:
      trust-issuer:
        type: temporary
      public-transparency-issuer:
        type: temporary
    trust-root:
      business-partner-id: "39f92e48-619e-4e92-8958-468ae138d8a3" # Demo Data CORE_ID_BP_GOV

cors:
  allowed-origins:
    - 'http://127.0.0.1:${server.port}'
    - 'http://localhost:${server.port}'

core-business:
  core-business-service-internal-base-url: "http://localhost:8200"

status-registry:
  write-base-url: ${core-business.core-business-service-internal-base-url}
